# Sistemas dinámicos

Los sistemas dinámicos son modelos de suma importancia en las ciencias. En general, un modelo dinámico intenta resolver la trayectoria temporal de alguna cantidad física como función de algún generador dinámico; este último usualmente representado de forma funcional.

En algunos casos, podemos modelar la dinámica de un estado genérico $y$ mediante la ecuación dinámica
\begin{equation}
\frac{dy}{dt} = f(t, y),
\end{equation}
sujeta a la condición inicial
\begin{equation}
y(t_0) = y_0.
\end{equation}

En esta notación, $y$ corresponde a un estado del sistema. Este estado puede ser representado mediante diferentes objetos matemáticos: desde cantidades escalares hasta matrices que representan cierto operador lineal. En la ecuación anterior, $t$ corresponde a la variable temporal.

El problema dinámico descrito anteriormente es usualmente conocido en el campo de las matemáticas aplicadas como **problema de condición inicial**. 

#### Laboratorio

Este tipo de problemas, el cual corresponde a algún modelo dinámico (para nombrar algunos ejemplos: sistemas electromagnéticos, dinámica de fluidos, sistemas caóticos, sistemas cuánticos, entre otros) será tema del curso más adelante. En este laboratorio, nuestro objetivo es aplicar conceptos de programación en `Python` utilizando `Jupyter Notebook`s para resolver el problema dinámico.

### Breve introducción a `Numpy`

En cálculos referentes a ciencia aplicada, una de las bibliotecas más importantes para diseñar aplicaciones científicas en `Python` es `Numpy`. `Numpy` está estructurado como un módulo, que debe ser importado para su uso.

Esto se realiza mediante la cláusula:

In [1]:
import numpy as np

La cláusula `import` importa el módulo a nuestro ambiente de programación, mientras que el *keyword* `as` implica que usaremos un acrónimo para invocar la funcionalidad del módulo; con el simple objetivo de no escribir la palabra `numpy` antes de cada función que invoquemos.

El objeto más importante del módulo `Numpy` es el `numpy.ndarray`. Este objeto es un contenedor (estructura de datos) que representa objetos como vectores, matrices o tensores. 

El constructor (estudiaremos contructores más adelante), se invoca pasando como argumento un `Python` `list`. Veamos por ejemplo como construir una matriz identidad 2x2 con esta estructura:

In [2]:
identityMatrix = np.array([[1,0], [0,1]])

print(identityMatrix)

[[1 0]
 [0 1]]


Note que pasamos una lista de listas para crear un objeto de mayor dimensión; i.e, una matrix. Los objetos creados con `np.array` contienen varias propiedades, tales como su tamaño y dichos atributos se accesan mediante el operador `.`:

In [3]:
identityMatrix.shape

(2, 2)

Los objetos se pueden operar matemáticamente de forma sencilla:

In [4]:
identityMatrix + identityMatrix

array([[2, 0],
       [0, 2]])

In [5]:
aEx = np.array([[0,1], [1,0]])

np.dot(aEx, aEx) # El producto matricial A*B

array([[1, 0],
       [0, 1]])

La documentación de `Numpy` se puede accesar mediante su página de referencia:
[NumPy](https://numpy.org)

## Soluciones a sistemas dinámicos

Los sistemas dinámicos y las soluciones numéricas a ecuaciones diferenciales son un tema importante de este curso que será estudiado más adelante. De momento, queremos utilizar este problema para familiarizarnos con el ambiente de programación científica.

Lo primero que vamos a hacer es describir el método numérico que vamos a utilizar para implementar la solución.

Vamos a utilizar el método Runge-Kutta de orden 4 para resolver el problema.

## Método Runge-Kutta de orden 4 (RK4)

Escriba las ecuaciones del método numérico utilizando LateX embedido en una celda de Markdown:

Cambie esta celda a tipo Markdown y utilice LateX para escribir las ecuaciones que 
se utilizan para resolver el problema utilizando el método RK4.

* $ k_1 = h\cdot f(x,t) $ 

* $ k_2 = h\cdot f(x+\frac{k_1}{2}, t+\frac{h}{2})$

* $ k_3 = h \cdot f(x+\frac{k_2}{2}, t+\frac{h}{2}) $

* $ k_4 = h \cdot f(x+k_3, t+h) $

* $ x(t+h) = x(t) + \frac{1}{6} (k_1 + 2k_2 + 2k_3 + k_4)$

## Ejemplo

Armados con esta metodología vamos a estudiar la solución de un problema dinámico genérico.

Asumamos que queremos estudiar la evolución temporal de un estado $\mathbf{y}(t)$. Este estado será representado mediante una matriz 2x2 que corresponde a algún operador lineal. La función que genra la dinámica del problema es 
$$
f(t, \mathbf{y}) = -{\rm{i}} [\mathbf{O}, \mathbf{y}(t)],
$$
donde $\mathbf{O}$ es otro operador lineal, ${\rm{i}}$ es la constante compleja y $[A, B] = AB - BA$ es un operación de conmutación. Note que **la función $f(t, \mathbf{y})$ no depende explícitamente de la variable temporal**.

En Python, la constante compleja se denota mediante:

In [ ]:
iConst = 1.0j

print(iConst)

La dinámica del problema depende intrínsicamente del operador $\mathbf{O}$. Escojamos el siguiente operador:

In [6]:
oOper = np.array([[0, 1], [1, 0]])

print(oOper)

[[0 1]
 [1 0]]


Dicho operador puede tener distintos significados físicos dependiendo del problema dinámico en cuestión. Puede representar un mapa algebraico, el generador dinámico de un sistema caótico, un Hamiltoniano, etc. 

Lo siguiente es difinir un estado inicial. De igual forma, dicho estado puede representar cantidades físicas de un sistema. Consideremos:

In [7]:
yInit = np.array([[1, 0], [0, 0]])

print(yInit)

[[1 0]
 [0 0]]


Note que el operador $\mathbf{O}$ no es diagonal, por lo cual esperamos que conforme avanza el tiempo, dicho operador modifica el estado $\mathbf{y}(t)$.

Implementemos la función $f(t, \mathbf{y})$ en Python. Para esto puede utilizar la función [np.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)

In [8]:
# Su código aquí
# El keyword pass está aquí para que la celda pueda ser interpretada sin necesidad de
# tener la función implementada. Su tarea es borrar el pass e implementar la función
def dyn_generator(oper, state):
    return -i*(np.dot(oper,state)-np.dot(state,oper))

Ahora tenemos que implementar la función que realiza la operación dinámica en `Python`. Escriba una función que implementa el método RK4:

In [ ]:
def rk4(func, oper, state, h):
    
     k_1 = h*func(oper, state) 

     k_2 = h*func(oper + 0.5*k_1, state + h/2)

     k_3 = h*func(oper + 0.5*k_2, state + h/2)

     k_4 = h*func(oper + k_3, state + h)

    return state + (1/6)*(k_1 + 2*k_2 + 2*k_3 + k_4)

Con estas funciones a nuestra disposición, podemos evaluar la dinámica temporal en una grilla temporal unidimensional. Utilice la función [np.linspace](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) para crear un arreglo de valores temporales:

In [11]:
# Su código aquí
# Utilice el nombre "times" para la variable que contiene el arreglo de valores temporales
# Utilice un valor final de t = 10.0
times = np.linspace(0,10,100)
print(times)


[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

Note que dicha función genera un arreglo con valores temporales homogéneos. Cual sería el valor de $h$?

In [ ]:
# Su código aquí
h = 100
# Utilice el nombre "h" para la variable que contiene el paso temporal

Ahora creamos una rutina para realizar la evolución temporal. Primero, necesitamos una copia del operador que representa el estado inicial. Esto se puede hacer con el método `copy()` del módulo `numpy`:

In [ ]:
# Haga un deep copy de yInit y llamele yCopy
# Los deep copies son muy importantes, analizaremos esto más adelante en el curso
yCopy = yInit.copy()

Y, finalmente, llamamos de manera iterativa la rutina `rk4()`, calculando el operador del estado del sistema $\mathbf{y}(t)$ a través del tiempo. A travéz del tiempo, vamos a guardar la entrada $(0, 0)$ y $(1, 1)$ de la matriz $\mathbf{y}(t)$. 

Para esto, vamos a inicializar dos arreglos que van a contener los valores con valores iniciales cero. Utilizamos el mismo tamaño del arreglo que contiene la variable independiente temporal: 

In [ ]:
stateQuant00 = np.zeros(times.size)
stateQuant11 = np.zeros(times.size)

Rutina principal: esta rutina realiza la evolución temporal.

In [ ]:
for tt in range(times.size):
    # Guarde el valor de las entradas (0,0) y (1,1) en los arreglos que definimos
    # Obtenga estos valores de las entradas de yInit
    # Código aquí ->
    
    # Invoque rk4 operando sobre yInit
    # y devuelva el resultado a un nuevo yN
    # Código aquí ->
    
    # Ahora asignamos yN a yInit
    # De esta manera, en la siguiente iteración, el operador de esta iteración se convierte en el inicial
    # de la siguiente iteración
    yInit = yN

Hagamos un gráfico de los resultados usando `matplotlib`:

In [ ]:
import matplotlib.pyplot as plt

# Código aquí ->
# Juegue con el valor de h para probar que utilizando valores grandes de h la dinámica se vuelve inestable